---
title: "data-manipulation"
author: "Joshua Munsey"
date: "2025-04-20"
output: pdf_document
---

```{r setup, include=FALSE}
library(DBI)
library(dplyr)

sqlite <- dbConnect(RSQLite::SQLite(), "../data/databases/exploration.db")
```

```{r data_load}
census_day <- dbGetQuery(sqlite, "SELECT * FROM CensusDay WHERE 
                          (ReportingCategory LIKE '%GN%' OR 
                          ReportingCategory LIKE '%RE%' OR
                          ReportingCategory = 'TA') AND 
                          NOT ReportingCategory = 'GN_X' AND
                          AggregateLevel = 'S' AND
                          NOT SchoolCode = 1 AND
                          NOT SchoolCode = 0")

acgr <- dbGetQuery(sqlite, "SELECT * FROM ACGR WHERE AggregateLevel = 'S' AND
                    NOT ReportingCategory = 'GX' AND
                    NOT SchoolCode = 1 AND
                    NOT SchoolCode = 0 AND
                    CharterSchool = 'No ' AND
                    DASS = 'No '")

ELA <- dbGetQuery(sqlite, "SELECT * FROM ELA")
Math <- dbGetQuery(sqlite, "SELECT * FROM Math")

# Replace all '*' characters with NA.
acgr[acgr == "*"] <- NA
census_day[census_day == "*"] <- NA
```

```{r convert_col_types}
census_day$GR_TK <- as.integer(census_day$GR_TK)
census_day$GR_KN <- as.integer(census_day$GR_KN)
census_day$GR_01 <- as.integer(census_day$GR_01)
census_day$GR_02 <- as.integer(census_day$GR_02)
census_day$GR_03 <- as.integer(census_day$GR_03)
census_day$GR_04 <- as.integer(census_day$GR_04)
census_day$GR_05 <- as.integer(census_day$GR_05)
census_day$GR_06 <- as.integer(census_day$GR_06)
census_day$GR_07 <- as.integer(census_day$GR_07)
census_day$GR_08 <- as.integer(census_day$GR_08)
census_day$GR_09 <- as.integer(census_day$GR_09)
census_day$GR_10 <- as.integer(census_day$GR_10)
census_day$GR_11 <- as.integer(census_day$GR_11)
census_day$GR_12 <- as.integer(census_day$GR_12)

acgr$AdultEd <- as.integer(acgr$AdultEd)
acgr$AdultEdRate <- as.numeric(acgr$AdultEdRate)
acgr$Biliteracy <- as.integer(acgr$Biliteracy)
acgr$BiliteracyRate <- as.numeric(acgr$BiliteracyRate)
acgr$CPP <- as.integer(acgr$CPP)
acgr$CPPRate <- as.numeric(acgr$CPPRate)
acgr$CohortStudents <- as.integer(acgr$CohortStudents)
acgr$DistrictCode <- as.integer(acgr$DistrictCode)
acgr$Dropout <- as.integer(acgr$Dropout)
acgr$DropoutRate <- as.numeric(acgr$DropoutRate)
acgr$Exemption <- as.integer(acgr$Exemption)
acgr$ExemptionRate <- as.numeric(acgr$ExemptionRate)
acgr$GED <- as.integer(acgr$GED)
acgr$GEDRate <- as.numeric(acgr$GEDRate)
acgr$Merit <- as.integer(acgr$Merit)
acgr$MeritRate <- as.numeric(acgr$MeritRate)
acgr$Other <- as.integer(acgr$Other)
acgr$OtherRate <- as.numeric(acgr$OtherRate)
acgr$RegHSDiploma <- as.integer(acgr$RegHSDiploma)
acgr$RegHSDiplomaRate <- as.numeric(acgr$RegHSDiplomaRate)
acgr$SPED <- as.integer(acgr$SPED)
acgr$SPEDRate <- as.numeric(acgr$SPEDRate)
acgr$SchoolCode <- as.integer(acgr$SchoolCode)
acgr$StillEnrolled <- as.integer(acgr$StillEnrolled)
acgr$StillEnrolledRate <- as.numeric(acgr$StillEnrolledRate)
acgr$UniReqs <- as.integer(acgr$UniReqs)
acgr$UniReqsPercent <- as.numeric(acgr$UniReqsPercent)

sapply(census_day, class)
sapply(acgr, class)
sapply(ELA, class)
sapply(Math, class)
```

```{r widen_df}
v_names <- c(
  "TOTAL_ENR", "GR_TK", "GR_KN", 
  "GR_01", "GR_02", "GR_03", 
  "GR_04", "GR_05", "GR_06", 
  "GR_07", "GR_08", "GR_09", 
  "GR_10", "GR_11", "GR_12"
)

wide_census_day <- reshape(
  census_day, idvar = c("AcademicYear", "SchoolCode"),
  timevar = "ReportingCategory", 
  direction = "wide", v.names = v_names 
)

acgr_v_names <- c(
  "AdultEd", "AdultEdRate",
  "Biliteracy", "BiliteracyRate",
  "CPP", "CPPRate",
  "CohortStudents", "DASS",
  "Dropout", "DropoutRate",
  "Exemption", "ExemptionRate",
  "GED", "GEDRate",
  "Merit", "MeritRate",
  "Other", "OtherRate",
  "RegHSDiploma", "RegHSDiplomaRate",
  "SPED", "SPEDRate",
  "StillEnrolled", "StillEnrolledRate",
  "UniReqs", "UniReqsPercent"
)

wide_acgr <- reshape(
  acgr, idvar = c("CharterSchool", "DASS", "SchoolCode", "Year"),
  timevar = "ReportingCategory",
  direction = "wide", v.names = acgr_v_names
)

wide_ela <- reshape(
  ELA, idvar = c("cdsCode", "Year"),
  timevar = "studentgroup",
  direction = "wide", v.names = c("currdenom", "currstatus")
)

wide_math <- reshape(
  Math, idvar = c("cdsCode", "Year"),
  timevar = "studentgroup",
  direction = "wide", v.names = c("currdenom", "currstatus")
)

wide_ela <- wide_ela[wide_ela$SchoolCode != 0,]
wide_math <- wide_math[wide_math$SchoolCode != 0,]
```

```{r write_table}
dbWriteTable(conn = sqlite, name = "CensusDayWide", value = wide_census_day)
dbWriteTable(conn = sqlite, name = "ACGRWide", value = wide_acgr)
dbWriteTable(conn = sqlite, name = "ELAWide", value = wide_ela)
dbWriteTable(conn = sqlite, name = "MathWide", value = wide_math)
dbListTables(conn = sqlite)
```

```{r cleanup, include=FALSE}
dbDisconnect(sqlite)
```